sudo: false

language: julia

os:
  - osx
  - linux

julia:
  - 1.0
  - 1.1
  - nightly

matrix:
  # fast_finish marks the build as passing even if allow_failures builds are still running
  fast_finish: true
  include:
    - os: windows
      arch: x64
      julia: 1.0
    - os: windows
      arch: x86
      julia: 1.0
      name: "Julia 1 (32bit)"
    - os: windows
      arch: x64
      julia: 1.1
    - os: windows
      arch: x86
      julia: 1.1
      name: "Julia 1.1 (32bit)"
  allow_failures:
    - julia: nightly
    - arch: x86

script:
  - make -j8 test
