name: test-windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.0.4, 1.1.1, 1.2.0-rc3, 1.3.0-alpha]
        os: [windows-latest]
    
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia ${{ matrix.julia-version }}"
        uses: julia-actions/setup-julia@v0.1.0
        with:
          version: ${{ matrix.julia-version }}
      - name: Test all exercises
        run: make test
